---
required_packages:
  - sudo
  - python3-pip
  - python3-virtualenv
  - git
  # Used for the sync_clients matching
  - gawk
  # Used to verify GPG signatures for mirrored packages
  - gnupg
  - iptables
  # Word List dictionary used by several roles to generate random data
  - "{{ package_name_words }}"
  - openssl
  - openvpn
