---
- name: OpenVPN | Add Clients | Set variables
  include_vars: ../../openvpn/defaults/main.yml

- name: OpenVPN | Add Clients | Register the OpenVPN server common name
  command: cat {{ openvpn_server_common_name_file }}
  no_log: true
  register: openvpn_server_common_name_result
  changed_when: false

- name: OpenVPN | Add Clients | Set server common name variable
  set_fact:
    openvpn_server_common_name: "{{ openvpn_server_common_name_result.stdout }}"

- name: OpenVPN | Add Clients | Add clients and generate keys
  include: add_gen_key.yml
  when: clients_to_add is defined

- name: OpenVPN | Add Clients | Add clients in database and generate passwords
  include: add_in_db.yml
  when: clients_to_add is defined and enable_auth_user_password

- name: OpenVPN | Add Clients | Send credentials to client
  ansible.builtin.include_role:
    name: send_credentials
  vars:
     client_to_add: "{{ item }}"
  with_items:
      - "{{ clients_to_add }}"